sudo: false
language: rust
rust: nightly
script:
- cargo build
- cargo test
after_success:
- .travis/release.sh
before_deploy:
- cargo doc
- .travis/publish.sh
- cargo package
- cargo publish --token $CARGO_TOKEN
deploy:
  provider: releases
  api_key:
    secure: R63t7UD46RuxkKTJRcLuK0tIezdZhd6BsLKbQ1L4b4H+7P+xfwuhDf+rC0HVw6qbJ3fCcGasYYxPUVkwYfqs9tIWORd+7JmBuQo6g1dsj+z/D6OSjn5XQ9YnmXHglGkADEneU/9SfDt+8xv171mJKgKZ6ZlIKg/mHDfbnM2DmiSwMigA/UPpVVVBcw1Bmk96umPeuLUSVOb67cy1F/56MQpv1Vzz0dfevjJxsA/BFbcBoDKFGwRaP8HqgDJYkbyCpN1EgM3lj99LmbCE0N7Jvl8x2VdAa0eIYXKAkc/oYCZsMhSYL5zFhcuRG/wOM875VqiEgK+aZMMhHYrWQWEkvycpM6ZvIahzj8JqO+NDqkN4xOGMKiUXLXjQHZpsDWh4le83V1xClc04R/QxSiJGVibw2O2H49L5bSW2idxBTOjSCH5tfxWdBvLL7JwJSlTPENGPPm3LZmVy5bRlSR2vE1vABwB5UmbhhT2NG9Ar6siXEzfxyG+Fp7a5GSJbDC3R5xRymUJIJQBI++A+3Am/Mgk4ZSzrIqMqfwof1xYM+Hd02xseWy2OqU89N+ufAaKe8SM+lQyr/lIQjUNBXMjlKYRd3BkmhBVleUv/0i5HabBG5q2tohyze59vdSA3FlxPjia1ON6gsmGS75EFVfJA2bQxVFu0wL9YbRBjfwCtPgQ=
  file: target/debug/libseax_svm.rlib
  on:
    repo: hawkw/seax_svm
    tags: true
env:
  global:
    secure: KHYk3sNFc1vNTgLRRDfGlYU3jqDgK1DBkr8NZR7gtQ/KaNq7PcHGNQ1Uoo6HOmhKLLha/ax+smq9hqtZGz9zH80ESIND37j+1rFVUFQ4aENNo7nCwn00vhk0nH9w0+AeTfgliMY+bf3OfPtGl+ra7LJaAVXn8YALcwd7bIUZOQ2EooYCLjR2HLxT880jdJSkx+aHW9FMQq+TosNqUl9w57a/R+N/CI5V2IMr4QM2Baq+U53hP0EbxEDoa8f9UoA7HPgjg+wlRe/p5GeybFcj7HdfCgAh47qVGC8Jj5g1tO4jzHfYumr9kVFUREqi4EC7nC/E4mFDw5KgTkpMXzoUEXKcwmX+j4b1U5H/uSyBS3GVzQhwsa6WiuuMgc00Z+7LJKMseDcgezlxg6ZTSkvewmt3bpL1WOTe5WK4xz6FPBGBOhywlACz2VVDUNYHPqd6p3sdGlxVR3FYgApbXwucCKsqS/a+RTvmPyMkxr9HuyNwNwFZviR4rA/pNerv3KSt2R7Ceo/MCFVLaqcazcwAUDegtLKPoCE5iWyKGyC0P79uTP3x+kxEKanRwFRvf+fGR0f+IabF/SJkjNPcIp5NKu7yiifnRuak3nj/K1a7p/PeJ/DeaiArxtCxBxzxdKf//g7FMtzFCZDVWTJRkiTMYkVaUK9baJRN9GuNvSjfbes=
