sudo: false
language: rust
rust: nightly

# dependencies for kcov
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

# load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

# the main build
script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo --only stable doc
env:
  global:
  # override the default `--features unstable` used for the nightly branch (optional)
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - secure: xHUGJn89lFSrNutHity1M+97tZjQ5ff0tjNbjDwchujL5BgP9aLVY3O7Wg3LoO/sWN8TYtO5sDVBy/8nV6HvVU28k/1ZLOQzDc2WeXIVBGdqOxB9QtLAkIa4aRHA6yhC65vI9zeTzGnOo166++4HvtU5DN5Bkq+Zm+AZxXVEZM+3AeiqaOLly6AzgUWCQf2TF8/aqU9K2sb6yBYsrBi8m4yMVYoC3pKlVlk6NbevhG059V/46zNQqDwbryLa+MPiRsnMuDVU2xAaKd4OAIxVNOfYmEETHnpZ1UNXMCc85XHOeu2+AVxJJzdb3U3jb7ixZ8z14ZwUBHzVgMv2p2lHvSL7TPQ/y+N4NOg7FEptxVzlzYT9h/5Nrx2sqVkgezzFf3L9vJ7W9CNHTBuW29gKpnNxuiFw0ZOU5c7St/tgccjzphOJaUvT1n7KuZinRktz7lIawShIuC8z1BChC2nDJoe650nvtUEETU++nj+rEdFmJwwGg+bz+vjsfFiXRxC6Fswe3Q7xrVrq+PDO51ZqZbOj1vj6Kxq1CdnHvvjNCb+wF4ihM4qf48Hnor80f+ciLwK5vENF6cMsSsTcEXHgXd1HwDGOkaBwkhQjwqg3fStuARmCQYmTnxuNHSNXnnazZq4MpRn4cqcr/ZeZsXOvJQ4BEA9HLacSD5Ii03D4u7A=
  - secure: KHYk3sNFc1vNTgLRRDfGlYU3jqDgK1DBkr8NZR7gtQ/KaNq7PcHGNQ1Uoo6HOmhKLLha/ax+smq9hqtZGz9zH80ESIND37j+1rFVUFQ4aENNo7nCwn00vhk0nH9w0+AeTfgliMY+bf3OfPtGl+ra7LJaAVXn8YALcwd7bIUZOQ2EooYCLjR2HLxT880jdJSkx+aHW9FMQq+TosNqUl9w57a/R+N/CI5V2IMr4QM2Baq+U53hP0EbxEDoa8f9UoA7HPgjg+wlRe/p5GeybFcj7HdfCgAh47qVGC8Jj5g1tO4jzHfYumr9kVFUREqi4EC7nC/E4mFDw5KgTkpMXzoUEXKcwmX+j4b1U5H/uSyBS3GVzQhwsa6WiuuMgc00Z+7LJKMseDcgezlxg6ZTSkvewmt3bpL1WOTe5WK4xz6FPBGBOhywlACz2VVDUNYHPqd6p3sdGlxVR3FYgApbXwucCKsqS/a+RTvmPyMkxr9HuyNwNwFZviR4rA/pNerv3KSt2R7Ceo/MCFVLaqcazcwAUDegtLKPoCE5iWyKGyC0P79uTP3x+kxEKanRwFRvf+fGR0f+IabF/SJkjNPcIp5NKu7yiifnRuak3nj/K1a7p/PeJ/DeaiArxtCxBxzxdKf//g7FMtzFCZDVWTJRkiTMYkVaUK9baJRN9GuNvSjfbes=
  - secure: VuWtvGpWBSFDLA69XASeCcA3/5aQ2tLFrvO46ur3kLoJyGIsfnB5qBTDfKagJk3EpbLtT0GN3pT8LtkaRQ1eVJGPpmsrG4tMMVyAvwgIUl6kdMLc6kNHQqLoNP1o6TZ2RYp1gCZNENH3iXAjmLHtHa6vCtPcqExO5/7vO9dW4Q6zStNQnG5JjU//YpEJuGQ1gY5wkI9yI02LEthYMdFtNQQSO/Is8iDWxBBWKpONxwYyb/K+teHklD4Jef7J8uWoXs/1Q12g16ft0tudnjuszHHiKRCwn4h8wKQ1CNXRMZNbb+UaKaaYTC6z0V+KoZEDC+E7avZVJolemuyeMyFYYCadT+Q9TFjRf5o7Q0wEzCJT5wwAeu8qc8piUnFYlRWGPZEknAZSgIinF1D+ejiVop4OUDCkQAdLtHHAu+aXl9GZrZt1ieg+nrxzgRV7c1PonVhtB3tyRNh8q10SaDb2hKxQywslaDWlOQBgVFLKSKKfVv1g9m2f/qvOyKdyk+XV/X9WfoNKwvkJX/g+rRDTjyZunPjAqoenoMhEqN9klDFmX7s4HoW+ZWsMZYhDFlJf0JvBhu+sukAegaqWCuy2JfVXLmNgTaGU1rjbwHyc/Dwekw+9x7XMJdFo3SvZnwZoH8UPeeDa/AZuYMSxIfwOBfCAm/+9ZuZxnKhLuN+qQpc=


after_success:
  # measure code coverage and upload to coveralls.io
  - travis-cargo coveralls --no-sudo
  # upload coverage to codecov.io
  - bash <(curl https://codecov.io/bash) 

before_deploy:
  # upload the documentation from the build
  - travis-cargo doc-upload
  # prepare the package for publishing to crates.io
  - cargo package
  # publish to crates.io
  - cargo publish --token $CRATES_TOKEN

deploy:
  provider: releases
  api_key:
    secure: R63t7UD46RuxkKTJRcLuK0tIezdZhd6BsLKbQ1L4b4H+7P+xfwuhDf+rC0HVw6qbJ3fCcGasYYxPUVkwYfqs9tIWORd+7JmBuQo6g1dsj+z/D6OSjn5XQ9YnmXHglGkADEneU/9SfDt+8xv171mJKgKZ6ZlIKg/mHDfbnM2DmiSwMigA/UPpVVVBcw1Bmk96umPeuLUSVOb67cy1F/56MQpv1Vzz0dfevjJxsA/BFbcBoDKFGwRaP8HqgDJYkbyCpN1EgM3lj99LmbCE0N7Jvl8x2VdAa0eIYXKAkc/oYCZsMhSYL5zFhcuRG/wOM875VqiEgK+aZMMhHYrWQWEkvycpM6ZvIahzj8JqO+NDqkN4xOGMKiUXLXjQHZpsDWh4le83V1xClc04R/QxSiJGVibw2O2H49L5bSW2idxBTOjSCH5tfxWdBvLL7JwJSlTPENGPPm3LZmVy5bRlSR2vE1vABwB5UmbhhT2NG9Ar6siXEzfxyG+Fp7a5GSJbDC3R5xRymUJIJQBI++A+3Am/Mgk4ZSzrIqMqfwof1xYM+Hd02xseWy2OqU89N+ufAaKe8SM+lQyr/lIQjUNBXMjlKYRd3BkmhBVleUv/0i5HabBG5q2tohyze59vdSA3FlxPjia1ON6gsmGS75EFVfJA2bQxVFu0wL9YbRBjfwCtPgQ=
  file: target/debug/libseax_svm.rlib
  on:
    repo: hawkw/seax_svm
    tags: true
