sudo: false
language: rust
rust: nightly
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- travis-cargo build
- travis-cargo test
- travis-cargo bench
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE="nightly"
  - secure: xHUGJn89lFSrNutHity1M+97tZjQ5ff0tjNbjDwchujL5BgP9aLVY3O7Wg3LoO/sWN8TYtO5sDVBy/8nV6HvVU28k/1ZLOQzDc2WeXIVBGdqOxB9QtLAkIa4aRHA6yhC65vI9zeTzGnOo166++4HvtU5DN5Bkq+Zm+AZxXVEZM+3AeiqaOLly6AzgUWCQf2TF8/aqU9K2sb6yBYsrBi8m4yMVYoC3pKlVlk6NbevhG059V/46zNQqDwbryLa+MPiRsnMuDVU2xAaKd4OAIxVNOfYmEETHnpZ1UNXMCc85XHOeu2+AVxJJzdb3U3jb7ixZ8z14ZwUBHzVgMv2p2lHvSL7TPQ/y+N4NOg7FEptxVzlzYT9h/5Nrx2sqVkgezzFf3L9vJ7W9CNHTBuW29gKpnNxuiFw0ZOU5c7St/tgccjzphOJaUvT1n7KuZinRktz7lIawShIuC8z1BChC2nDJoe650nvtUEETU++nj+rEdFmJwwGg+bz+vjsfFiXRxC6Fswe3Q7xrVrq+PDO51ZqZbOj1vj6Kxq1CdnHvvjNCb+wF4ihM4qf48Hnor80f+ciLwK5vENF6cMsSsTcEXHgXd1HwDGOkaBwkhQjwqg3fStuARmCQYmTnxuNHSNXnnazZq4MpRn4cqcr/ZeZsXOvJQ4BEA9HLacSD5Ii03D4u7A=
  - secure: hOaCd97R1ixJZzYZolcMBlqEtm/WAnIjNfUdIAne6GecWrpIrpUL6K9kXCv/LAOp0T2JzcbT/a9AlwSgzse5ZTqsf39letwtmCP4iMnoX6cqBGL39jTXMCQKYRhOKQiINhpu1pBnTyxHJAzKry+dglbaYHqapu/v7VR18Zqn0IpbawKw/C0xZzmnNZ8HUco30JVtRC8vNOUvoJNtlz1I7Q9H8GLBJ3E6ACfnz+pQomtuTcw28bkXxFC2WtaQAXWHbkJujVs+9RrD4EfbHJL1fkqQeJn/aoxfN0JBb3pTPWSi/ydPJUDXKrZkRqfAmb3YcTqOSO4jg+EpstNhHLf8nnz9pjMbxJEsLP/yTVSPefcTehwDnSK/0+1mmgWNBrXMzrapJUxVWSlc4oAvwk+mbju/LmVLZrP7uWUuPjRHCMOzpvZu62bUqq5j7QewTzQop6w56UbhRmlGhWqLD/oZbtZh/FwQ5TslsQtERAAPRV3lwIsE9ePC4rgNJi1petECCAkPufr+SmL8oReB8aa0NC5ojnc9lGxA8DIqW/9IwILBwRMCR+9iUO5ukclc7KxmayeCBZZJxCX5JRylfUhGarl+l8kgd7AE61YMO8dZ08U5ERlTgmoixtTcZB7wJY7JpBN7kg/O9wFp9VWw0FcQVwbyoqBlv7C9CkaMc2E/QpI=
  - secure: E+00NmwXknVUGsmmcDsEkuLPJCTM6/GXUspvWAhN7i58eSY/zn4pG0Kl0bCy8/uMpdo8TsJZ1844qgrufqlxnrieIURb9xi/+niB5Eld5PR4G9kQqKcSAyIXy4RUKmWeq4V/DUiYHs1wEQm+gWmVyAa6uDVuCfXOqJ9l792kl6ITOMYOLgXpCR9S5SUDICHBBRCedF/Rd6ok2igDu6Sn90PO+/VO5JGLe9jfSg3dl9KNUc8waLT/ra8a0Xd5v1r9dlMR+FuBIKgtk8bkVhGlEjYoeO7IT3MITH7XMCVQCVrS0/1RjIcLIQClDFtcOFIIbtgWS7LndYeHzHmKIsuO+QZTC0LmLq3HjfPhey1SZ9y0IC/Fbq1ph3uUnBKiXEom9LMsj0pl8GlKwbbbW0G6IsMzNl17M3yk/wj8FPftNXQP9uCdYSucKWPJ29rq2XfYXPDn0wr0foVJWSknJJ375Q3vBpUn9jVsldESx6AC7nUKnZWrqMhVbfTOR6q1GMMUbanVtGHgQLPOaKMD3fyBI/XgwiJ/VcWP3A7IpwmZjAFVkGCGCxN5AESRH7hy/YbP+UhxEluE0rnnzcrA69wMR7IQYwrjuK7WroMIMPfPaJhUB+q0d+PZEw9B8YReIujqXYEAeJoUEFWGWJuBbGL+3NSk/SusDxASTj3l8kTIVo0=
after_success:
- travis-cargo coveralls --only nightly --no-sudo
- bash <(curl https://codecov.io/bash)
before_deploy:
- travis-cargo doc
- travis-cargo doc-upload
- travis-cargo build -- --release
- travis-cargo package -- --features nightly 
- travis-cargo publish --token $CRATES_TOKEN
deploy:
  provider: releases
  api_key:
    secure: R63t7UD46RuxkKTJRcLuK0tIezdZhd6BsLKbQ1L4b4H+7P+xfwuhDf+rC0HVw6qbJ3fCcGasYYxPUVkwYfqs9tIWORd+7JmBuQo6g1dsj+z/D6OSjn5XQ9YnmXHglGkADEneU/9SfDt+8xv171mJKgKZ6ZlIKg/mHDfbnM2DmiSwMigA/UPpVVVBcw1Bmk96umPeuLUSVOb67cy1F/56MQpv1Vzz0dfevjJxsA/BFbcBoDKFGwRaP8HqgDJYkbyCpN1EgM3lj99LmbCE0N7Jvl8x2VdAa0eIYXKAkc/oYCZsMhSYL5zFhcuRG/wOM875VqiEgK+aZMMhHYrWQWEkvycpM6ZvIahzj8JqO+NDqkN4xOGMKiUXLXjQHZpsDWh4le83V1xClc04R/QxSiJGVibw2O2H49L5bSW2idxBTOjSCH5tfxWdBvLL7JwJSlTPENGPPm3LZmVy5bRlSR2vE1vABwB5UmbhhT2NG9Ar6siXEzfxyG+Fp7a5GSJbDC3R5xRymUJIJQBI++A+3Am/Mgk4ZSzrIqMqfwof1xYM+Hd02xseWy2OqU89N+ufAaKe8SM+lQyr/lIQjUNBXMjlKYRd3BkmhBVleUv/0i5HabBG5q2tohyze59vdSA3FlxPjia1ON6gsmGS75EFVfJA2bQxVFu0wL9YbRBjfwCtPgQ=
  file: target/release/libseax_svm.rlib
  on:
    repo: hawkw/seax_svm
    rust: nightly
    tags: true
